# Generated by Django 6.0.4 on 2026-04-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviepromotion',
            options={'verbose_name': 'Акция фильма', 'verbose_name_plural': 'Акции фильмов'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='moviepromotion',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='moviepromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.promotion', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='movies',
            field=models.ManyToManyField(blank=True, through='cinema.MoviePromotion', to='cinema.movie', verbose_name='Фильмы'),
        ),
    ]
