# Generated by Django 6.0.4 on 2026-04-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_director_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
