# Generated by Django 6.0.4 on 2026-04-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_ticket_unique_together_ticket_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='expires_at',
        ),
    ]
